eureka:
  client:
    service-url:
      defaultZone: http://keepgoing-alb-1744092232.ap-northeast-2.elb.amazonaws.com/eureka/
  instance:
    hostname: config-server
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30  # 리스 갱신 간격
    lease-expiration-duration-in-seconds: 90  # 리스 만료 기간