eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:18800/eureka/
  instance:
    hostname: config-server
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30  # 리스 갱신 간격
    lease-expiration-duration-in-seconds: 90  # 리스 만료 기간