# auction - application-local.yml
server:
  port: 6600

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/member
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      uri: mongodb://root:examplepassword@localhost:27017/default?authSource=admin
    redis:
      host: localhost
      port: 6379
      password: ""
      database: 0

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        # SQL 포매팅 출력
        format_sql: true
        # SQL 실행 시 주석 포함
        use_sql_comments: true
    show_sql: true
  cloud:
    config:
      enabled: false

springdoc:
  swagger-ui:
    path: /swagger-ui
    operations-sorter: method
    tags-sorter: alpha
eureka:
  client:
    enabled: false
