# auction - application.yml

spring:
  application:
    name: auction-service

management:
  endpoints:
    web:
      discovery:
        enabled: true
      exposure:
        include: "*"

product:
  topic:
    auction-pending-start:
      v1: product.auctionPendingStart.v1
    auction-started:
      v1: product.auctionStarted.v1