# auction - application.yml

spring:
  application:
    name: auction-service

management:
  endpoints:
    web:
      discovery:
        enabled: true
      exposure:
        include: "*"

topic:
  auction-pending-start:
    v1: product.auctionPendingStart.v1
  auction-started:
    v1: product.auctionStarted.v1
  auction-ended:
    v1: product.auctionEnded.v1
  winner-confirm:
    v1: auction.winnerConfirm.v1