# auction - application.yml
server:
  port: 6600

spring:
  application:
    name: auction-service

  data:
    mongodb:
      auto-index-creation: true
  kafka:
    template:
      observation-enabled: true

  kafka:
    consumer:
      group-id: auction-service-group
      # offset 커밋 기록이 삭제되었거나, 브로커에서 보관중인 로그범위에서 오프셋이 유효하지 않은 경우
      # 어디서부터 메시지를 읽기 시작할지 정해주는 설정
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        isolation.level: read_committed # 트랜잭션 메시지 읽기 안전성
      # key 는 String 으로 역직렬화
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # value 는 Json java 객체로 역직렬화 하겠다
      # properties 추가 설정이나 ConsumerFactory 에서 추가 설정 필요
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    listener:
      # 필수: @KafkaListener 에서 Acknowledgment 사용 가능
      # MANUAL 수동 커밋 모드
      ack-mode: MANUAL
      # 컨슈머 스레드 개수 (옵션)
      concurrency: 3

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 브로커의 리더 + 모든 ISR 에 쓰기 성공 후 ACK
      acks: all
      retries: 3

springdoc:
  swagger-ui:
    path: /swagger-ui
    operations-sorter: method
    tags-sorter: alpha

management:
  endpoints:
    web:
      discovery:
        enabled: true
      exposure:
        include: "*"

topic:
  auction-pending-start:
    v1: product.auctionPendingStart.v1
  auction-started:
    v1: product.auctionStarted.v1
  auction-ended:
    v1: product.auctionEnded.v1
  winner-confirm:
    v1: auction.winnerConfirm.v1
  auction-failed:
    v1: order.auctionfailed.v1

stomp:
  relay:
    port: 61613
    login: artemis
    passcode: artemis
