server:
  port: 5500

spring:
  application:
    name: order-service

  config:
    import: ""
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 10
      properties:
        enable.idempotence: true

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: order-service-consumer-group
      auto-offset-reset: earliest
      enable-auto-commit: false

    listener:
      ack-mode: manual
      observation-enabled: true

    template:
      observation-enabled: true

jdbc:
  datasource-proxy:
    enabled: true
    include-parameter-values: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  tracing:
    sampling:
      probability: 1.0
    enabled: true

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

topic:
  order:
    created: order.created.v1
    completed: order.completed.v1
    refund: order.refund.v1
    refund-success: order.refund-success.v1
    refund-fail: order.refund-fail.v1
    failed: order.failed.v1

  bid:
    order:
      request: bid.winnerconfirm.v1
      inventory-confirm-timeout: bid.inventoryconfirmtimeout.v1

  auction:
    order:
      request: acution.winnerconfirm.v1

  payment:
    completed: payment.approved.v1
    refund-completed: payment.refund.v1
    refund-failed: payment.refund-fail.v1
    failed: payment.failed.v1

consumer:
  group:
    payment: payment-consumer-group
    bid: bid-consumer-group

retry:
  count:
    max: 5