# member - application-prod.yml
spring:
  config:
    activate:
      on-profile: prod
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://${RDS_END_POINT}/member
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
#  data:
#    mongodb:
#      uri:
#    redis:
#      host:
#      port:
#      password: ""
#      database: 0

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    show-sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

  kafka:
    # 로컬에서 Docker로 띄운 브로커 외부 포트에 맞춰 설정 (docker-compose의 EXTERNAL 매핑)
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: AWS_MSK_IAM
      sasl.jaas.config: "software.amazon.msk.auth.iam.IAMLoginModule required;"
      sasl.client.callback.handler.class: software.amazon.msk.auth.iam.IAMClientCallbackHandler


eureka:
  client:
    enabled: false