# member - application-prod.yml
spring:
  config:
    activate:
      on-profile: prod
    import: "optional:configserver:"

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
  datasource:
    url: jdbc:postgresql://${RDS_END_POINT}/p_member
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
#  data:
#    mongodb:
#      uri:
#    redis:
#      host:
#      port:
#      password: ""
#      database: 0

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    show-sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

  kafka:
    # 로컬에서 Docker로 띄운 브로커 외부 포트에 맞춰 설정 (docker-compose의 EXTERNAL 매핑)
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}


eureka:
  client:
    service-url:
      defaultZone: http://keepgoing-alb-1744092232.ap-northeast-2.elb.amazonaws.com/eureka/
  instance:
    hostname: ${spring.application.name}:${random.value}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30  # 리스 갱신 간격
    lease-expiration-duration-in-seconds: 90  # 리스 만료 기간